main: 
	g++ -std=c++11 Tools.cpp Strategy_life_creator.cpp Strategy_Life.cpp Strategy_fire_creator.cpp Strategy_Fire.cpp Save_File.cpp Parser.cpp Online_Creator.cpp Online.cpp Offline_Creator.cpp Offline.cpp main.cpp Game_Run.cpp Game_Life_Creator.cpp Game_Life.cpp Game_Fire_Creator.cpp Game_Fire.cpp Executor.cpp -o main
clean:
	rm -rf *.o